#!/usr/bin/env bash

set -euo pipefail

./configure \
    --with-debug \
    --prefix=/var/lib/nginx-mid \
    --sbin-path=/usr/sbin/nginx-mid \
    --modules-path=/usr/lib/nginx-mid/modules \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/run/nginx/nginx.pid \
    --lock-path=/run/nginx/nginx.lock \
    --http-client-body-temp-path=/var/lib/nginx-mid/tmp/client_body \
    --http-proxy-temp-path=/var/lib/nginx-mid/tmp/proxy \
    --http-fastcgi-temp-path=/var/lib/nginx-mid/tmp/fastcgi \
    --http-uwsgi-temp-path=/var/lib/nginx-mid/tmp/uwsgi \
    --http-scgi-temp-path=/var/lib/nginx-mid/tmp/scgi \
    --with-threads \
    --with-file-aio \
    --without-pcre2 \
    --with-http_v3_module \
    --with-http_ssl_module \
    --with-http_v2_module \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_xslt_module=dynamic \
    --with-http_image_filter_module=dynamic \
    --with-http_geoip_module=dynamic \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_auth_request_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_degradation_module \
    --with-http_slice_module \
    --with-http_stub_status_module \
    --with-http_perl_module=dynamic \
    --with-mail=dynamic \
    --with-mail_ssl_module \
    --with-stream=dynamic \
    --with-stream_ssl_module \
    --with-stream_realip_module \
    --with-stream_geoip_module=dynamic \
    --with-stream_ssl_preread_module \
    --add-dynamic-module="$1"
