
ldap_server my-ldap {
	binddn "cn=Manager,dc=my-domain,dc=com";
	binddn_passwd secret;

	users_url "ldap://localhost/ou=users,dc=my-domain,dc=com?uid?one";
	groups_url "ldap://localhost/ou=groups,dc=my-domain,dc=com?cn?one";

	member_attribute_is_dn on;
	member_attribute member;

	require group qa;
}

ldap_server my-ldap-lunae {
	binddn "cn=Manager,dc=my-domain,dc=com";
	binddn_passwd secret;

	users_url "ldap://localhost/ou=users,dc=my-domain,dc=com?uid,gid?one";
}

auth_ldap_cache_enabled on;

server {
	listen 80 default_server;

	error_log stderr debug;

	location / {
		dav_next dav-test {
			auth ldap;
			servers my-ldap${LDAP2};
		}
	}
}

${FULLPORTINCLUDE}
